# Reddit deprecated functions
def createUser(self, profile):
    self.loadPage(Reddit.creation_url)
    sleep(3)
    monkey.click()
    btn = self.driver.find_element(By.XPATH, '//input[@name="email"]')
    btn.click()
    debug('clicking email')
    sleep(1)
    monkey.type(f'{profile["email"]}')
    debug('typing email')
    sleep(1)
    btn = self.driver.find_element(By.XPATH, '//button[@data-step="email"]')
    btn.click()
    sleep(3)
    btn = self.driver.find_element(By.XPATH, '//input[@name="username"]')
    btn.click()
    debug('clicking username')
    monkey.type(f'{profile["username"]}')
    debug('typing username')
    monkey.next()
    monkey.type(f'{profile["password"]}')
    debug('typing password')
    monkey.captcha()
    error('Click on create account button -- Press enter to continue')
    input()
    return True